# Uses https://github.com/marketplace/actions/close-stale-issues

name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *' # Every day at 1:30 AM
    
permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          debug-only: false

          exempt-issue-labels: 'high-impact-bug,in-progress,needs-triage,not-stale'
          exempt-pr-labels: 'not-stale,needs-triage'

          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          
          stale-issue-message: 'This issue is stale because it has been open 2 weeks with no activity. It will be closed in 2 days unless there is new activity. See [MAINTAINERSHIP.md#issues](https://github.com/Hopding/pdf-lib/blob/master/docs/MAINTAINERSHIP.md#issues) for details.'
          stale-pr-message: 'This PR is stale because it has been open 3 weeks with no activity. It will be be closed in 2 days unless there is new activity. See [MAINTAINERSHIP.md#pull-requests](https://github.com/Hopding/pdf-lib/blob/master/docs/MAINTAINERSHIP.md#pull-requests) for details.'
          close-issue-message: 'This issue was closed because it went 2 weeks with no activity. Feel free to leave a comment if you feel it should be reopened!'
          close-pr-message: 'This PR was closed because it went 3 weeks with no activity. Feel free to leave a comment if you feel it should be reopened!'
          
          days-before-issue-stale: 14
          days-before-pr-stale: 21
          days-before-issue-close: 2 
          days-before-pr-close: 2
          
